### ISSUE TITLE
Boxzilla and IE 11

### ISSUE THREAD

**Issue by newyorkwebdesign** [ibericode/boxzilla-wp#107]
Even though conditions:everywhere is set and test mode has been turned off, Boxzilla does not displaying in IE 11. I also cleared browser’s caches and there are no relevant errors in console.

Site URL: https://karay.creativecrib.com/

Please reply

**Comment by arnelap** [comment]
I've confirmed a bug in the scroll trigger and anchor mechanism in IE11 and below. 
Other triggers do work, such as time on site or manual javascript triggers.

**Comment by dannyvankooten** [comment]
Hey, sorry for the delay but this should be fixed in the most recent Boxzilla version. Version 3.1.17. Cheers!

**Comment by newyorkwebdesign** [comment]
Good News!! Thanks

**Comment by newyorkwebdesign** [comment]
Actually, I tested your demos (https://demo.boxzillaplugin.com/2015/05/13/a-post-where-the-box-slides-in-at-comments-section/) in IE11 and it doesn't seem to work.

**Comment by dannyvankooten** [comment]
Hey David, you're absolutely right. We  have yet to install the update on our demo site. (:

On August 30, 2017 10:38:47 PM GMT+02:00, David Radovanovic <notifications@github.com> wrote:
>Actually, I tested your demos
>(https://demo.boxzillaplugin.com/2015/05/13/a-post-where-the-box-slides-in-at-comments-section/)
>in IE11 and it doesn't seem to work.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/ibericode/boxzilla-wp/issues/107#issuecomment-326111980

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by newyorkwebdesign** [comment]
Though it doesn't seem to be working on my site in IE11 even after update. Can you please check https://karay.creativecrib.com/ and verify? Thanks!

**Comment by dannyvankooten** [comment]
Hi @newyorkwebdesign,

Can you please try clearing your browser cache? For me the box popped-up on IE11 just now, so I'm guessing your cache is still loading the older JavaScript file.
