### ISSUE TITLE
Generate Javascript:Boxzilla.show(nnn) link from shortcode

### ISSUE THREAD

**Issue by arnelap** [ibericode/boxzilla-wp#108]
Because Wordpress doens't allow every role to use JS and sometimes it's filtered out as soon as you go to the WYSIWYG editor. 

[boxzillalink-1234]  something like that would be nice. 

<a href="[boxzillalink-1234]">Click me!</a>

**Comment by arnelap** [comment]
from https://wordpress.org/support/topic/javascript-filtered-out-of-href/#post-9474456

**Comment by dannyvankooten** [comment]
https://kb.boxzillaplugin.com/shortcode-boxzilla-link/
