### ISSUE TITLE
possible cf7 form conflict

### ISSUE THREAD

**Issue by arnelap** [ibericode/boxzilla-wp#114]
only in later versions. 

see: https://wordpress.org/support/topic/boxzilla-conflict-with-contact-form-7/#new-post

**Comment by cfaria** [comment]
Test [https://andreaamoretti.com/test/](https://andreaamoretti.com/test/)

It's not always happening. Look at the checkbox to accept the agreements. If it's visible everything works fine, but if you reload you may not see it. The checkbox is only visible if I unwrap it using this function in jQuery (I need it unwrapped to style it): 

`$(document).ready(function(){
  $('.wpcf7-acceptance').unwrap();
});`

So sometimes the box content is loaded before the ready jQuery function fires up, then it works (both my checkbox and CF7 Ajax). But sometimes the box content is loaded after the ready jQuery function fires up (checkbox not visible nor CF7 Ajax available).

Weird...

**Comment by cfaria** [comment]
Seems to be working now every time I reload...

Bummer

**Comment by cfaria** [comment]
To better explain the behaviour with the checkbox two images worth a thousand words:

Checkbox not visible (CF7 Ajax doesn't work either)

![image](https://user-images.githubusercontent.com/756658/32796465-246b6552-c96f-11e7-9ae4-2eb9f75a4a0e.png)

Checkbox visible (CF7 does work too)

![image](https://user-images.githubusercontent.com/756658/32796470-29271ece-c96f-11e7-82f9-eaa370e8d7df.png)

**Comment by arnelap** [comment]
When you disable Boxzilla and add the form to a normal page, does the checkbox work, or do you still have this issue?

**Comment by arnelap** [comment]
I could not reproduce the issue on my testing site. 

If you are still experiencing any problem please create a ticket at https://wordpress.org/support/plugin/boxzilla or further support.
When you do, please include a link to where we can test the box and please also create a normal page where you include the same form, but not in a box, so we can see if the error only occurs in when the form is in a box.

​Thanks for letting us know!!
