### ISSUE TITLE
Click to open on mobile

### ISSUE THREAD

**Issue by pridraga** [ibericode/boxzilla-wp#116]
Hi Gents,

Great plugin however noticed an issue on mobile when using the 'click to launch' setting.  I am using the URL method ie #boxzilla-1, noting that it works on desktop. 

As a test I set the pop-up to show on 65% and it worked fine on both mobile and desktop.  Appears to be an issue with click to open on mobile only.

Cheers,
P

**Comment by arnelap** [comment]
What mobile OS and What mobile browser did you test this on?

**Comment by pridraga** [comment]
Hello,

It was tested on Android and IOS devices, both Chrome and Safari. Same
behaviour. Screen started to scroll up and make scrolling back down glitchy.



On 29 Nov. 2017 19:02, "Arne Lap" <notifications@github.com> wrote:

What mobile OS and What mobile browser did you test this on?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ibericode/boxzilla-wp/issues/116#issuecomment-347781949>,
or mute the thread

**Comment by pridraga** [comment]
Hi Arne,

Any luck with this bug?

M

**Comment by arnelap** [comment]
I've just tried to reproduce this issue on Chrome on my Android, and everything worked fine in the latest version.
