### ISSUE TITLE
Conflict with plugin Forget About Short Code Buttons

### ISSUE THREAD

**Issue by rpavlis** [ibericode/boxzilla-wp#118]
When both plugins are installed, Boxzilla will not open the Media, using Add Media button in editor.

When Forget About Short Code Buttons is deactivated, Boxzilla has no problem adding media.

**Comment by dannyvankooten** [comment]
Hi @rpavlis,

Do you have a link to this plugin, preferably somewhere I can download it? A quick search for "Forget About Short Code Buttons" yielded no results for me.

Thanks in advance!

**Comment by dannyvankooten** [comment]
Hi @rpavlis,

Never mind, I just found it when ditching the whitespace between "Short" and "Code". However this seems to be an issue in that plugin and not really something we can do something about from within Boxzilla itself.

We could make sure that that other plugin never loads on the Boxzilla post pages but it really is something for them to fix properly, I'm afraid.

**Comment by rpavlis** [comment]
Danny - do you have a recommendation of a button plugin that does work with Boxzilla?
