### ISSUE TITLE
Boxzilla not working with Mailerlite shortcode or HTML script

### ISSUE THREAD

**Issue by rpavlis** [ibericode/boxzilla-wp#119]
Created a box and inserted Mailerlite shortcode for an embedded form- does not work. The shortcode works fine in a WP post without a Boxzilla box and as a widget.

Tried their Java script (<script type="text/javascript" src="https://static.mailerlite.com/data/webforms/669456/z1c1f4.js?v11"></script>) - it did not work either.

Tried their HTML script and it does add basic information from the embed form, but none of the formatting. 

The HTML code is:

<style>
    @import url('https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i&subset=cyrillic,cyrillic-ext,latin-ext');
    #mlb2-7018436,
    #mlb2-7018436 *,
    #mlb2-7018436 a:hover,
    #mlb2-7018436 a:visited,
    #mlb2-7018436 a:focus,
    #mlb2-7018436 a:active {
        overflow: visible;
        position: static;
        background: none;
        border: none;
        bottom: auto;
        clear: none;
        cursor: default;
        float: none;
        letter-spacing: normal;
        line-height: normal;
        text-align: left;
        text-indent: 0;
        text-transform: none;
        visibility: visible;
        white-space: normal;
        max-height: none;
        max-width: none;
        left: auto;
        min-height: 0;
        min-width: 0;
        right: auto;
        top: auto;
        width: auto;
        z-index: auto;
        text-shadow: none;
        box-shadow: none;
        outline: medium none;
    }
    
    #mlb2-7018436 a:hover {
        cursor: pointer !important;
    }
    
    #mlb2-7018436 h4 {
        font-weight: normal;
    }
    
    #mlb2-7018436 .subscribe-form {
        padding: 20px;
        width: 300px !important;
        border: 4px solid #8E44AD !important;
        background: #f6f6f6 none !important;
        border-radius: 15px !important;
        box-sizing: border-box !important;
    }
    
    #mlb2-7018436 .ml-block-form {
        margin-bottom: 0px;
    }
    
    #mlb2-7018436 .subscribe-form .form-section {
        margin-bottom: 20px;
        width: 100%;
    }
    
    #mlb2-7018436 .subscribe-form .form-section.mb10 {
        margin-bottom: 10px;
        float: left;
    }
    
    #mlb2-7018436 .subscribe-form .form-section.mb0 {
        margin-bottom: 0px;
    }
    
    #mlb2-7018436 .subscribe-form .form-section h4 {
        margin: 0px 0px 10px 0px !important;
        padding: 0px !important;
        color: #765431 !important;
        font-family: 'Open Sans', sans-serif !important;
        font-size: 28px !important;
        line-height: 100%;
        text-align: center !important;
    }
    
    #mlb2-7018436 .subscribe-form .form-section p,
    #mlb2-7018436 .subscribe-form .form-section li {
        line-height: 150%;
        padding: 0px !important;
        margin: 0px 0px 10px 0px;
        color: #000000 !important;
        font-family: 'Open Sans', sans-serif !important;
        font-size: 14px !important;
    }
    
    #mlb2-7018436 .subscribe-form .form-section a {
        font-size: 14px !important;
    }
    
    #mlb2-7018436 .subscribe-form .form-section .confirmation_checkbox {
        line-height: 150%;
        padding: 0px !important;
        margin: 0px 0px 15px 0px !important;
        color: #000000 !important;
        font-family: 'Open Sans', sans-serif !important;
        font-size: 12px !important;
        font-weight: normal !important;
    }
    
    #mlb2-7018436 .subscribe-form .form-section .confirmation_checkbox input[type="checkbox"] {
        margin-right: 5px !important;
    }
    
    #mlb2-7018436 .subscribe-form .form-section .form-group {
        margin-bottom: 15px;
    }
    
    #mlb2-7018436 .subscribe-form .form-section .form-group label {
        float: left;
        margin-bottom: 10px;
        width: 100%;
        line-height: 100%;
        color: #000000 !important;
        font-family: 'Open Sans', sans-serif !important;
        font-size: 14px !important;
    }
    
    #mlb2-7018436 .subscribe-form .form-section .checkbox {
        width: 100%;
        margin: 0px 0px 10px 0px;
    }
    
    #mlb2-7018436 .subscribe-form .form-section .checkbox label {
        color: #000000 !important;
        font-family: 'Open Sans', sans-serif !important;
        font-size: 14px !important;
    }
    
    #mlb2-7018436 .subscribe-form .form-section .checkbox input {
        margin: 0px 5px 0px 0px;
    }
    
    #mlb2-7018436 .subscribe-form .form-section .checkbox input[type=checkbox] {
        -webkit-appearance: checkbox;
        opacity: 1;
    }
    
    #mlb2-7018436.ml-subscribe-form .form-group .form-control {
        width: 100%;
        font-size: 13px;
        padding: 10px 10px;
        height: auto;
        font-family: Arial;
        border-radius: 0px;
        border: 1px solid #cccccc !important;
        color: #000000 !important;
        background-color: #FFFFFF !important;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
        clear: left;
    }
    
    #mlb2-7018436.ml-subscribe-form button {
        border: none !important;
        cursor: pointer !important;
        width: 100% !important;
        border-radius: 10px !important;
        height: 40px !important;
        background-color: #C0392B !important;
        color: #FFFFFF !important;
        font-family: 'Arial', sans-serif !important;
        font-size: 16px !important;
        text-align: center !important;
        padding: 0 !important;
        margin: 0 !important;
        position: relative!important;
    }
    
    #mlb2-7018436.ml-subscribe-form button.gradient-on {
        background: -webkit-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.2) 100%);
        background: -o-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.2) 100%);
        background: -moz-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.2) 100%);
        background: linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.2) 100%);
    }
    
    #mlb2-7018436.ml-subscribe-form button.gradient-on:hover {
        background: -webkit-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.3) 100%);
        background: -o-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.3) 100%);
        background: -moz-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.3) 100%);
        background: linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.3) 100%);
    }
    
    #mlb2-7018436.ml-subscribe-form button[disabled] {
        cursor: not-allowed!important;
    }
    
    #mlb2-7018436.ml-subscribe-form .form-section.ml-error label {
        color: red!important;
    }
    
    #mlb2-7018436.ml-subscribe-form .form-group.ml-error label {
        color: red!important;
    }
    
    #mlb2-7018436.ml-subscribe-form .form-group.ml-error .form-control {
        border-color: red!important;
    }
    
    #mlb2-7018436 .ml-vertical-align-center {
        text-align: center;
        display: block;
    }
    
    #mlb2-7018436 .ml-block-success,
    #mlb2-7018436 form.ml-block-form {
        display: inline-block;
        width: 300px;
    }
    
    @media (max-width: 768px) {
        #mlb2-7018436 {
            width: 100% !important;
        }
        #mlb2-7018436 form.ml-block-form,
        #mlb2-7018436.ml-subscribe-form .subscribe-form {
            width: 100% !important;
        }
    }
</style>
<div id="mlb2-7018436" class="ml-subscribe-form ml-subscribe-form-7018436">
    <div class="ml-vertical-align-center">
        <div class="subscribe-form ml-block-success" style="display:none">
            <div class="form-section">
                <h4>Garden Fundamentals Newsletter</h4>
                <p>Thank you! An email has been sent so you can confirm you are human.</p>
            </div>
        </div>
        <form class="ml-block-form" action="https://app.mailerlite.com/webforms/submit/z1c1f4" data-id="669456" data-code="z1c1f4" method="POST" target="_blank">
            <div class="subscribe-form">
                <div class="form-section mb10">
                    <h4>Garden Fundamentals Newsletter</h4>
                    <p>Sign up for a free monthly newsletter containing dozens of garden and garden design articles.</p>
                </div>
                <div class="form-section">
                    <div class="form-group ml-field-name ml-validate-required">
                        <input type="text" name="fields[name]" class="form-control" placeholder="First Name*" value="" autocomplete="name" x-autocompletetype="name" spellcheck="false" autocapitalize="off" autocorrect="off">
                    </div>
                    <div class="form-group ml-field-email ml-validate-required ml-validate-email">
                        <input type="email" name="fields[email]" class="form-control" placeholder="Email*" value="" autocomplete="email" x-autocompletetype="email" spellcheck="false" autocapitalize="off" autocorrect="off">
                    </div>
                </div>
                <input type="hidden" name="ml-submit" value="1" />
                <button type="submit" class="primary">
                    Subscribe Today
                </button>
                <button disabled="disabled" style="display: none;" type="button" class="loading">
                    <img src="https://static.mailerlite.com/images/rolling@2x.gif" width="20" height="20" style="width: 20px; height: 20px;">
                </button>
            </div>
        </form>
        <script>
            function ml_webform_success_7018436() {
                var $ = ml_jQuery || jQuery;

                $('.ml-subscribe-form-7018436 .ml-block-success').show();
                $('.ml-subscribe-form-7018436 .ml-block-form').hide();
            };
        </script>
    </div>
</div>
<script type="text/javascript" src="https://static.mailerlite.com/js/w/webforms.min.js?v3772b61f1ec61c541c401d4eadfdd02f"></script>

**Comment by dannyvankooten** [comment]
Hi @rpavlis,

Could you please post the complete embed cone between backticks (`) please? GitHub also has an "Insert code" button in their editor.

That will allow us too the entire embed code so that I can run some tests with it.

Thanks in advance!

**Comment by dannyvankooten** [comment]
Hi @rpavlis,

After some additional digging into Mailerlite's embed code it seems that they are using `document.write` to render their sign-up form. I am afraid that this is not compatible with the way Boxzilla is developed, as it is a rather ancient technique which will block page rendering.

Since Boxzilla itself is loaded and initialised after the entire page has fully loaded (so not to slow down your site unnecessary) this is too late for Mailerlite to do their (dirty) work. 

I am afraid the only solution is to contact Mailerlite and ask them whether they have a more modern means of embedding a form on your website, one that does not utilise `document.write`.

Sorry I can't be of more help right now. I wish we could...
