### ISSUE TITLE
bug with CF7

### ISSUE THREAD

**Issue by KaueAlves** [ibericode/boxzilla-wp#123]
When i use ContactForm7 Shortcode in box, sometimes ajax fail.
To work properly, I am using an old version that does not contain the bug.

Version: 3.1.13

How can I fix this, to update without any problem?

**Comment by dannyvankooten** [comment]
Hi @KaueAlves,

Any details on what kind of error you are getting when it fails?

**Comment by arnelap** [comment]
Please create a ticket at https://wordpress.org/support/plugin/boxzilla or further support on this issue. 
When you do, please include a link to where we can test the box and please also create a normal page where you include the same form, but not in a box, so we can see if the error only occurs in when the form is in a box. 
And of course the exact / full error you are getting as Danny ask above. 

​Thanks for letting us know!!
