### ISSUE TITLE
Doesn't work with parameters in URL

### ISSUE THREAD

**Issue by UVLabs** [ibericode/boxzilla-wp#128]
I'm certain this classifies as a different issue from #127 

If you have the option set to not show the box on URL /newsletter/ it still shows if there are parameters in the URL, example... I had to turn off the newsletter box I have because it was showing to users who came from a Facebook ad campaign promoting this newsletter page which contained UTM tags.

I did try adding an option to exclude this exact URL which contained the UTM tag but from testing it still showed up.

**If** and **if not** are good filters but **_containing_** is also a very powerful filter option you can add to the plugin. Other solutions such as Sumome has the "if URL containing" option...

**Comment by dannyvankooten** [comment]
Hey @UVLabs,

Sorry for the somewhat late reply, GDPR had me quite busy.

I think you're absolutely right that this is a separate issue, I'll take a stab at it later this week!

**Comment by UVLabs** [comment]
@dannyvankooten thank you but you added contains but not "not contains" basically you have "load box if..." so I want to set it to "load box if..." "does not contain..." "utm_source=ad" or some other parameter in the URL
