### ISSUE TITLE
Ability to order which pop-up shows first

### ISSUE THREAD

**Issue by martinbon** [ibericode/boxzilla-wp#137]
Having an easy way of sorting which pop-up shows first would be quite useful on multi pop-up site setups. Currently the only way to arrange the queue is with triggers.

In my case have around 3 pop-ups out of which a Cookie notice pop-up should be first in order. But since the appearance of a box is seemingly random, it's quite the balancing act to achieve good results on multiple sites.

**Comment by arnelap** [comment]
closed in favour of issue 109
