### ISSUE TITLE
Why can't I query the posts generated by Boxzilla?

### ISSUE THREAD

**Issue by jamesfacts** [ibericode/boxzilla-wp#139]
Hi Boxzilla folks,

First off—fantastic plugin! I have used it in a few builds and it's a great balance between usable interface and powerful features and loads fast and I love it. 

I'm trying to set up a particular site with the ability to A/B test multiple pop-ups. I see the `boxzilla_load_box` filter, which seems perfect. Great! I want to query all the posts that are Boxzilla boxes and then pick one at random. Ok, easy:

```
function boxzilla_randomize( $load, $box_id ) {

  $box_args = [
	  'post_status' => 'publish',
    'meta_query' => [
      [
        'key' => 'boxzilla_options',
        'compare' => 'EXISTS'
      ]
    ]
  ];

  $box_query = new \WP_Query( $box_args );

  if ( $box_query->has_posts() ) {
    write_log("hey, I got one");
  }

  // return $box_id;
}

add_filter( 'boxzilla_load_box', __NAMESPACE__.'\\boxzilla_randomize', 10, 2 );
```

And yet, I get nothing. I can query for any other meta key and it works fine... I am totally stumped. I know there are posts with `boxzilla_options`—why can't I query them?

**Comment by arnelap** [comment]
We only use git for development related issues.  I saw you emailed us about this, we will reply there instead.
