### ISSUE TITLE
support multiple boxes on one page  / one overlay per box

### ISSUE THREAD

**Issue by jaysn** [ibericode/boxzilla-wp#140]
Since there is only one singe overlay on the page which gets toggled, you will run into weird situations if you use an even number of boxes which will end up with no boxes shown but a visible overlay... the solution to this might be generating one overlay div per box and toggle this instead. this way only the overlay of the closed box will get hidden..

imho this was already intended in some way as the script.js shows us that everything is grouped together in Box instances which shows us, there is an intent to support more than one box at a time.

think this should be done quite fast and easy.

**Comment by jaysn** [comment]
i see that this problem is more an issue to [boxzilla.js](https://github.com/ibericode/boxzilla.js). should i open up an dedicated issue over there ? as fixing the compiled js in this repo wouldnt be the real solution 😄

**Comment by jaysn** [comment]
raised the coresponding issue here ibericode/boxzilla.js#19

**Comment by dannyvankooten** [comment]
Hey @jaysn,

Thank you for the PR, the code definitely looks good and I'm open to merge it. That said, I'm actually not quite sure whether we need an overlay per box as it sounds like an issue with the overlay logic in the first place where we could get away with a single overlay. 

Can you please describe to me how I can replicate the issue with the visible overlay despite no boxes being visible?
