### ISSUE TITLE
aria-modal accessibility attribute

### ISSUE THREAD

**Issue by hchouhan** [ibericode/boxzilla-wp#152]
Add accessibility tags to the pop-up

Some details:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html

**Comment by hchouhan** [comment]
https://secure.helpscout.net/conversation/1376743847/27686/

**Comment by dannyvankooten** [comment]
Closed in 0d495be16cbc6c6738ab1a68b50424e2e4786e43
