### ISSUE TITLE
Add screen sizes or device types to box rules

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/boxzilla-wp#63]
So people can make a "mobile only" box. 

Right now these rules are handled server-side and we probably want to keep it that way, but we can make a distinction between client-side and server-side rules so that user doesn't have to worry about this.

**Comment by hchouhan** [comment]
Any Progress?

**Comment by dannyvankooten** [comment]
Is this a joke?

**Comment by arnelap** [comment]
this was added in  3.1.11 - March 22, 2017
