### ISSUE TITLE
Box is only showing up at the bottom of the page

### ISSUE THREAD

**Issue by everetthill** [ibericode/boxzilla-wp#67]
The boxes are now only showing up at the bottom of the page and not sliding into view. Check out the Boxzilla call to action box at www.everetth.com to see what I'm referring to.

**Comment by dannyvankooten** [comment]
Hi @everetthill,

Is this problem still persisting? I'd love to take a closer look, but looking at your site it seems the box is now positioned top-right and working fine.

Let me know please.

**Comment by everetthill** [comment]
Thanks for checking on it. It looks like the issue somehow got fixed. I'm not sure if it was a bug with my site or the plugin, but I think everything is good now.

www.everetth.com
Sent from my phone




On Thu, Jul 28, 2016 at 5:35 AM -0400, "Danny van Kooten" <notifications@github.com> wrote:












Hi @everetthill,



Is this problem still persisting? I'd love to take a closer look, but looking at your site it seems the box is now positioned top-right and working fine.



Let me know please.

**Comment by dannyvankooten** [comment]
Perfect, glad to hear it @everetthill - could very well have been a cache issue. :-)
