### ISSUE TITLE
After closing box on mobile, page scrolls down.

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/boxzilla-wp#72]
Happens on iPhones, at least.

See: https://secure.helpscout.net/conversation/231085400/7170/?folderId=491455

**Comment by frankblundt** [comment]
Prevent default doesn't appear to fix the issue.

**Comment by dannyvankooten** [comment]
Some more details on this issue, fix seems lengthy.... https://stackoverflow.com/questions/29001977/safari-in-ios8-is-scrolling-screen-when-fixed-elements-get-focus

**Comment by dannyvankooten** [comment]
2ffa29ef776d36b065c64b6d6779d4027a374a22 should workaround this issue in MobileSafari
