### ISSUE TITLE
`Auto-show box` features not working

### ISSUE THREAD

**Issue by paulkirspuu** [ibericode/boxzilla-wp#96]
Hello

We've been having difficulties with the 2 functionalities regarding `Auto-show box` feature,
- yes, when at x % of page height
- yes, when at element #example

Do you have any idea what could cause that?

We currently have 2 active Boxzilla boxes and would like to add the #example element trigger to the third one.

Thanks

**Comment by dannyvankooten** [comment]
Hi @paulkirspuu,

So the box is not showing even though you set-up the "auto show box setting" correctly? Do you have a link to your site so we can take a look? This probably depends on your theme styling, so it's hard top give a definite general answer.
